### ISSUE TITLE
clussiana@psi.org on build #5: This is a neg test and the only thing that's showing here is…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#1]
Feedback from clussiana@psi.org : This is a neg test and the only thing that's showing here is the age of the patient. No test result and no sex.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57b166ad632de401007bfee7/dd1527a6-af5f-4d4a-b6a5-1f419a80375a.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Aug 17 2016 13:27:12 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>5</td></tr></table>

 [Link to buddybuild feedback from build 5](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57b4663073dffc0100a79c9c&bnum=5)

**Comment by ifoche** [comment]
Hi @cristinaelle , just guessing. Can you please attach how does the following question...

![leonlg_q1](https://cloud.githubusercontent.com/assets/10931645/17746808/2e3091c0-64b2-11e6-865e-28cf2ef9d127.png)

...renders in your device? It looks like your device is not properly rendering the lao font.

**Comment by cristinaelle** [comment]
![image](https://cloud.githubusercontent.com/assets/12784825/17751281/20433f0a-64cf-11e6-8760-aefa8a23e282.png)
