### ISSUE TITLE
clussiana@psi.org on build #10: In case the OU selected is not in the system, the prompt…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#11]
Feedback from clussiana@psi.org : In case the OU selected is not in the system, the prompt still says "Contact PS Kenya at 0123456789".

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57bc349ec88f110100b8a3fe/554f4a43-34c8-4246-8f56-195c2cf44ead.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Aug 23 2016 16:55:00 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>10</td></tr></table>

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57bc7fe49a06af01001ebeb0&bnum=10)

**Comment by ifoche** [comment]
@cristinaelle I see this feedback image all in blank. Can you please describe a little bit more the problem?

**Comment by cristinaelle** [comment]
When I type an OU that is not listed within the OUs available, I've got a prompt box that tells me to call PSK (PS Cambodia) at 0123456789. This is not relevant for the Laos version of the MCS app. We should change the content of that prompt box.

**Comment by ifoche** [comment]
@cristinaelle you're right. However, just in case, these strings it's possible to edit them in the [translation server](https://poeditor.com/projects/po_edit?id_language=91&id=63217). If you edit them and them tell us, we can generate a new release with those changes included (don't worry this time, we'll do it)

**Comment by ifoche** [comment]
@cristinaelle can we consider this task as done? would you please move it to done in that case?
