### ISSUE TITLE
clussiana@psi.org on build #10: Something is wrong with the math behind this table. Today…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#12]
Feedback from clussiana@psi.org : Something is wrong with the math behind this table. Today I've submitted a total of 4 surveys and they're not showing up here. A few minutes ago I had 2 suspected cases and now there's only one.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57bc349ec88f110100b8a3fe/82e3c3d7-4079-4321-b8f1-90cf175fe90c.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Aug 24 2016 15:49:55 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>10</td></tr></table>

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57bdc22330c0b70100b5efbc&bnum=10)

**Comment by ifoche** [comment]
@cristinaelle maybe this is related to #13? Can you confirm that the problem was suspected cases was not taking not tested into account?

**Comment by cristinaelle** [comment]
No, this is not related to #13 because in this case the Monitor module hasn't updated its figures at all after sending a survey.

**Comment by ifoche** [comment]
ok, just remember that monitoring is only showing what is actually sent, and doesn't take into account what is in the queue to be sent...so if I'm not bad, if you send a survey and you quickly go to the monitoring module, you won't see what you've just sent...but after it's really in the server. However, we will review this procedure to look for any problem in it

**Comment by ifoche** [comment]
@cristinaelle  can we consider this task as done? would you please move it to done in that case?
