### ISSUE TITLE
rebecca@psilaos.org on build #10: text overlapping image

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#16]
Feedback from rebecca@psilaos.org : text overlapping image 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57bc349ec88f110100b8a3fe/f637c7d1-3635-4a15-abc2-0e34bb781785.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Aug 30 2016 01:33:41 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>10</td></tr><tr><td>Device type</td><td>SCH-I545</td></tr><tr><td>Screen size</td><td>1080</td></tr><tr><td>Screen size</td><td>1080px by 1920px</td></tr><tr><td>Battery</td><td>64% Unplugged</td></tr><tr><td>Memory free</td><td>462 MB / 1807 MB</td></tr></table>

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57c4e275f7885b0100a00ebd&bnum=10)

**Comment by ifoche** [comment]
Text is overlapping here because the device resolution is very high (1080x1920). Thanks for sharing it, we'll test with those resolutions and try to fix it asap

**Comment by ifoche** [comment]
we're not addressing this issue yet waiting for the image with the embedded text for the treatment question. Do we go for it even without that artwork?

**Comment by ifoche** [comment]
For the rest of the issues we have finished with the implementation. Do you want us to create a bb with the rest? BTW. Making this text not to overlap with the image in any type of screen would mean a redesign of some of the components of the layout, that finally would imply more than we initially thought. Do you still want to address this issue?

**Comment by rbeccapotter** [comment]
@ifoche How many hours do you think it would take (to re-design the components of the layout to fix the text overlapping etc)?

**Comment by ifoche** [comment]
Hi @rbeccapotter, sorry for not answer here, but I think @rodmelia already answered to this by mail. Just for the record, I think it would imply around 25-35 hours.

**Comment by ifoche** [comment]
Just closing this issue, as I think it's being already solved in #15
