### ISSUE TITLE
rebecca@psilaos.org on build #10: text overlapping images. also hard to read white font should…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#17]
Feedback from rebecca@psilaos.org : text overlapping images. also hard to read white font should be black to match the design. maybe here if dynamic text is not reliable on many phone types we use flat images instead  ,, 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57bc349ec88f110100b8a3fe/27ef1b13-1ab1-482d-9e49-0896dbfb93d5.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Aug 30 2016 01:55:22 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>10</td></tr><tr><td>Device type</td><td>SCH-I545</td></tr><tr><td>Screen size</td><td>1080</td></tr><tr><td>Screen size</td><td>1080px by 1920px</td></tr><tr><td>Battery</td><td>57% Unplugged</td></tr><tr><td>Memory free</td><td>414 MB / 1807 MB</td></tr></table>

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57c4e78af7885b0100a00f7b&bnum=10)

**Comment by ifoche** [comment]
This looks like a duplicate of #16

**Comment by rbeccapotter** [comment]
Keeping this separate from #16. This screen we will probably replace dynamic text with embedded text so it renders well on any device. On hold until I get an updated graphic.

**Comment by rbeccapotter** [comment]
@ifoche The revised artwork for Q5 Treatment is signed off and can be found here:
https://drive.google.com/open?id=0BzWNKmbLqoIReVlhSlN5eEZGcW8
Note we finally decided to use the embedded text on this screen instead of dynamic.

**Comment by ifoche** [comment]
@rbeccapotter ok, thank you. We'll incorporate it to the app and create a new bb version in order to let you test it and check how it looks like.

**Comment by ifoche** [comment]
@rbeccapotter new bb is out with this embedded text in the image. Please let us know any further problem you could find with this release.

**Comment by ifoche** [comment]
@rbeccapotter can we consider this task as done? would you please move it to done in that case?
