### ISSUE TITLE
rebecca@psilaos.org on build #10: number of submissions = 3 but there is one positive,  one…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#19]
Feedback from rebecca@psilaos.org : number of submissions = 3 but there is one positive,  one negative , one not tested severe and one not tested pregnant.so I don't think the calculation is working. side note: # submissions will be the same as # suspected cases. we can fix the semantics with the rest of monitor module but want to flag the error in calculation  .    , 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57bc349ec88f110100b8a3fe/a1e1f7ee-e916-4bc5-a244-464071fcd47b.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Aug 30 2016 02:16:00 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>10</td></tr><tr><td>Device type</td><td>SCH-I545</td></tr><tr><td>Screen size</td><td>1080</td></tr><tr><td>Screen size</td><td>1080px by 1920px</td></tr><tr><td>Battery</td><td>52% Unplugged</td></tr><tr><td>Memory free</td><td>355 MB / 1807 MB</td></tr></table>

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57c4ec60f7885b0100a01010&bnum=10)

**Comment by ifoche** [comment]
In the image I see the dropdown menu with "6 months" selected. That means the numbers are summarizing the last month, so any other submission you (or any other one in that OU if you pulled the data from the server after (s)he made his/her submission) are included in the summary. Can you please do a pull, go to monitoring, take note of the values before you make the submissions, and then do your testing? otherwise numbers may be altered artificially. 

However, take also into account that in the version you're using (we're fixing it) the "not tested" cases are not included in the "suspected cases". 

It's also clear that we need to agree again the distribution of the monitoring module. I've reviewed the specifications documents and I think there were several incoherences between the initial design and the subsequent editions. Could you please summarize in a google doc the final and definitive desired monitoring table so we can adapt the current one to that behaviour?

**Comment by rbeccapotter** [comment]
@ifoche the monitor table  can be updated according to the formulas on Monitor tab here: https://docs.google.com/spreadsheets/d/1703GttDy8uUIRkNfkJqxIJzWBYL5M3bRPd_u7TD6JM0/edit#gid=1277797201

**Comment by ifoche** [comment]
@rbeccapotter can we consider this task as done? would you please move it to done in that case?
