### ISSUE TITLE
rebecca@psilaos.org on build #10: after selecting Pv, popup prompt 3 "in case of Pv or mix,…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#20]
Feedback from rebecca@psilaos.org : after selecting Pv, popup prompt 3 "in case of Pv or mix, refer" is missing from the work flow  

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57bc349ec88f110100b8a3fe/e6002914-2b72-498c-ad8d-5ed9eed91c1d.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Aug 30 2016 02:47:22 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>10</td></tr><tr><td>Device type</td><td>SCH-I545</td></tr><tr><td>Screen size</td><td>1080</td></tr><tr><td>Screen size</td><td>1080px by 1920px</td></tr><tr><td>Battery</td><td>46% Unplugged</td></tr><tr><td>Memory free</td><td>299 MB / 1807 MB</td></tr></table>

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57c4f3baf7140d01005be165&bnum=10)

**Comment by ifoche** [comment]
I've just tested it and it works for me. Remember that the pop-up is shown after selecting the drug...did you selected the drug?

**Comment by rbeccapotter** [comment]
@ifoche I tested this again and bug is still there after selecting correct drug. I entered:
Q3 Age = 22
Q4 Test result = Pv
Q5 Treatment= ACT 6x4
And it goes to Q6 Phone number with no pop-up for Prompt 4 "In case of Pv or Pv+Pf give coartem and refer".

**Comment by ifoche** [comment]
@rbeccapotter We think it probably comes from a direct update from the previous build, where that pop-up was not present in the app. The point is that this pop-up is "modelled" as a question in the DB. The DB is loaded on the first boot of the app, and a direct update do not update the questions unless we specifically do it with a special script. We do not include this scripts yet, as the app is not yet in production, to reduce the development time, but in the other hand, not including these scripts means that a new release with a DB update needs to remove the app and reinstall to properly work. We should tell you whenever there's a DB update to prevent you and ask you to reinstall, but this time we forgot to do it...so can you please remove the app and install it again and test? Sorry for not saying it before.
