### ISSUE TITLE
kathelyn@psilaos.org on build #12: text change - in excel sheet

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#26]
Feedback from kathelyn@psilaos.org : text change - in excel sheet

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57db204d9786940100a83afc/c7e201d4-fe70-42b3-af37-ebd6893355b0.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Sep 23 2016 03:17:58 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>12</td></tr><tr><td>Device type</td><td>SM-J120H</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 800px</td></tr><tr><td>Battery</td><td>37% Unplugged</td></tr><tr><td>Memory free</td><td>252 MB / 960 MB</td></tr></table>

 [Link to buddybuild feedback from build 12](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57e49ee6199fde010041b16c&bnum=12)

**Comment by rbeccapotter** [comment]
See Q1 here: https://drive.google.com/open?id=0BzWNKmbLqoIRTVdWdlpvRGtzZ1U
