### ISSUE TITLE
kathelyn@psilaos.org on build #12: can we shift to the right ?

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#30]
Feedback from kathelyn@psilaos.org : can we shift to the right ?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57db204d9786940100a83afc/4df0d928-25f9-46a2-9eb6-a8c2b2434d8b.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Sep 23 2016 03:24:05 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>12</td></tr><tr><td>Device type</td><td>SM-J120H</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 800px</td></tr><tr><td>Battery</td><td>36% Unplugged</td></tr><tr><td>Memory free</td><td>247 MB / 960 MB</td></tr></table>

 [Link to buddybuild feedback from build 12](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57e4a055bf479601002ca194&bnum=12)

**Comment by rbeccapotter** [comment]
@ifoche  I think what makes the most sense here is to have the green section as dynamic text and the rest of the image (answers 1-4) embedded text so that it renders correctly on any device. Is this possible to mix and match dynamic/embedded in the same page?

**Comment by ifoche** [comment]
@rbeccapotter the green text is always dynamic, so you're asking here to embed the text in the images also for this question, right? This is not in ready column so we're not doing it right now...please move it to ready if you're happy with us going for it.

**Comment by rbeccapotter** [comment]
@ifoche actually I'm asking to keep green text dynamic; but the text for the answers would be embedded. Anyways, the artwork needs to be switched outso you can use this: https://drive.google.com/open?id=0BzWNKmbLqoIRWWFOS3h5WG80c3c

And the translation for the green text (it needs to be changed) is here: https://drive.google.com/open?id=0BzWNKmbLqoIRTVdWdlpvRGtzZ1U
