### ISSUE TITLE
kathelyn@psilaos.org on build #12: should say send in Lao. see excel sheet

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#31]
Feedback from kathelyn@psilaos.org : should say send in Lao. see excel sheet 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57db204d9786940100a83afc/6c016566-7cdf-42c4-b6a4-3835c73439b6.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Sep 23 2016 03:25:19 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>12</td></tr><tr><td>Device type</td><td>SM-J120H</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 800px</td></tr><tr><td>Battery</td><td>35% Unplugged</td></tr><tr><td>Memory free</td><td>253 MB / 960 MB</td></tr></table>

 [Link to buddybuild feedback from build 12](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57e4a09fce88e00100ba1c70&bnum=12)

**Comment by rbeccapotter** [comment]
See Q3 here for translation: https://drive.google.com/open?id=0BzWNKmbLqoIRTVdWdlpvRGtzZ1U

**Comment by rbeccapotter** [comment]
@ifoche The orange button should have Lao text, it's still in English. The word is:    ສົ່ງ

**Comment by ifoche** [comment]
@rbeccapotter that string is automatically translated to the language of the phone. If you check it in a Lao phone, it should be ok
