### ISSUE TITLE
kathelyn@psilaos.org on build #14: it looks like dynamic text in white is still overlapping the…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#32]
Feedback from kathelyn@psilaos.org : it looks like dynamic text in white is still overlapping the embedded image 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57e853223b5c09010037f1b5/d126f40c-b2a6-4834-a131-18776449eedc.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Sep 28 2016 08:28:58 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>14</td></tr><tr><td>Device type</td><td>SM-J120H</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 800px</td></tr><tr><td>Battery</td><td>63% Unplugged</td></tr><tr><td>Memory free</td><td>284 MB / 960 MB</td></tr></table>

 [Link to buddybuild feedback from build 14](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57eb7f4adf7e310100e302f6&bnum=14)

**Comment by ifoche** [comment]
It's not supposed to happen in build 14 if you installed it from zero or you evolved from the immediately previous version to 14. Can you please uninstall and install the app, and test it again? (it has to be with the DB changes and the migration between versions)

**Comment by ifoche** [comment]
@rbeccapotter can you confirm this is not happening anymore?

**Comment by rbeccapotter** [comment]
@ifoche I uninstalled/reinstalled build 14 and it is still appearing this way.
