### ISSUE TITLE
rebecca@psilaos.org on build #14: Artwork change requedted

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#33]
Feedback from rebecca@psilaos.org : Artwork change requedted

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57e853223b5c09010037f1b5/0b9540d2-94a5-42fd-9472-520c40fa7cf0.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Oct 03 2016 06:25:15 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>14</td></tr><tr><td>Device type</td><td>SM-T231</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>73% Unplugged</td></tr><tr><td>Memory free</td><td>314 MB / 1289 MB</td></tr></table>

 [Link to buddybuild feedback from build 14](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57f1f9cb03ec450100ac9df3&bnum=14)

**Comment by rbeccapotter** [comment]
The green dynamic text stays the same. The updated image is here: https://drive.google.com/open?id=0BzWNKmbLqoIRMHJqYzBfczRQX2M
