### ISSUE TITLE
rebecca@psilaos.org on build #14: Artwork change rewuested plus text in orange box.

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#34]
Feedback from rebecca@psilaos.org : Artwork change rewuested plus text in orange box.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57e853223b5c09010037f1b5/0e894766-2987-42ff-af26-1ae540266ac0.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Oct 03 2016 06:49:13 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>14</td></tr><tr><td>Device type</td><td>SM-T231</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>68% Unplugged</td></tr><tr><td>Memory free</td><td>503 MB / 1289 MB</td></tr></table>

 [Link to buddybuild feedback from build 14](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57f1ff6913546201003f3f35&bnum=14)

**Comment by rbeccapotter** [comment]
Actually, I think that the text in the orange box is embedded not dynamic (??). 

The updated artwork is here: https://drive.google.com/open?id=0BzWNKmbLqoIRd0w5OTYyMEkzVE0

**Comment by ifoche** [comment]
@rbeccapotter yes, that text is dynamic. So the translation is wrong? is the correct translation [here](https://drive.google.com/open?id=0BzWNKmbLqoIRTVdWdlpvRGtzZ1U)?

**Comment by rbeccapotter** [comment]
@ifoche yes, the translation for "next" on Prompt 4. Thanks.
