### ISSUE TITLE
rebecca@psilaos.org on build #14: Translation change

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#35]
Feedback from rebecca@psilaos.org : Translation change 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57e853223b5c09010037f1b5/26ec0742-fdcd-4e0b-8ef5-c485906b65b1.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Oct 04 2016 08:52:28 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>14</td></tr><tr><td>Device type</td><td>SM-T231</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>57% Unplugged</td></tr><tr><td>Memory free</td><td>359 MB / 1289 MB</td></tr></table>

 [Link to buddybuild feedback from build 14](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57f36dccf5ff780100c4ca02&bnum=14)

**Comment by rbeccapotter** [comment]
Green text should be changed to match Q6 here and also the "send" in English should render in Lao. https://drive.google.com/file/d/0BzWNKmbLqoIRTVdWdlpvRGtzZ1U/view

**Comment by ifoche** [comment]
@rbeccapotter, in the settings of that phone it is configured in Lao as language, right?
