### ISSUE TITLE
Update from translation server

### ISSUE THREAD

**Issue by rbeccapotter** [EyeSeeTea/SurveillanceLaosApp#37]
In the next release, please update the strings from translation server.

**Comment by rbeccapotter** [comment]
@ifoche The translations for English version (highlighted in green) are in a new file here: https://drive.google.com/open?id=0BzWNKmbLqoIRaElLNHNfZXMyM28

For Lao version,  need to update with Lao text in the final review screen  "Please check before transmitting."

**Comment by ifoche** [comment]
Thanks @rbeccapotter, we'll do it asap

**Comment by rbeccapotter** [comment]
@ifoche I don't think all of the translations updated. Can you check:
Q1a [I know answers are embedded, but question?]
Q4 
Prompt 2 (invalid result): orange buttons
Prompt 3
Prompt 4: green text says 'submission' instead of 'refer'

https://drive.google.com/drive/u/1/folders/0BzWNKmbLqoIRenFHMUxnckhlV2c

**Comment by ifoche** [comment]
@rbeccapotter I think there was a problem with the document associated to the first link in your first comment and we somehow got a different document. Definitively the new translation system we're working on (moving everything to POEditor) is going to improve these problems. However, I think that sometimes google doc is not properly opening xlsx docs, so maybe it would be better if the document is directly a google sheets doc. Now you linked to a google drive folder, and I've downloaded the xsls file to review it carefully. 

Sorry for the inconveniences, we will release a new version tomorrow so you can test it before your presentation the 18th.

**Comment by rbeccapotter** [comment]
Yes...the reason I've been keeping an .xlsx is because 1) the Lao team says that something strange happens with the Lao text in GoogleDoc and 2) the pictures mapped to the questions weren't showing up properly. Sorry about that, I know it's less than ideal.

**Comment by ifoche** [comment]
You're right, you had already remarked that problem with font rendering in Google Sheets. No problem, thanks for reviewing it carefully. We'll solve this very soon.

**Comment by ifoche** [comment]
To avoid more backs and forths on this. Please @rbeccapotter can you confirm the changes on translations are as follows?
Q1 - Question changed from "Has the patient been tested?" to "Was the patient tested?"
Q1a - Question changed from "Why the patient was not tested?" to "Reason not tested"
Q1a warning - Change orange button from "Send" to "OK" 
Q2 - (It's highlighted but I see no change here)
Q3 - Change orange button from "Send" to "OK"
Q4 - Change question from "Result of blood test" to "RDT Result"
Q5p3 - Change body from "Treatment selected does not match patient's age" to "ACT dosage selected is not correct for the patient's age. Please try again."
Q5p3 - Change orange button from "Please re-check" to "Go back"
Q4p4 - Change question from "Submission" to "Refer"
Q4p4 - Change orange button from "Continue" to "OK"
Q6 - Change orange button from "Send" to "OK".
Review screen - The question is highlighted but I see no change in the text, so I assume no change here.

Is this a good summary of needed changes?

**Comment by rbeccapotter** [comment]
For the invalid result screen:
Q4p2: Orange button 1: Change 'Please try again' to 'Repeat RDT'
Q4p2: Orange button 2: Change 'Not bad check' to 'Wrong selection - go back'

Everything else above is good. Thanks.
