### ISSUE TITLE
rebecca@psilaos.org on build #19:

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#38]
Feedback from rebecca@psilaos.org : 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/580092aa5d80530100085e40/0f4c86db-61bc-4824-94a6-87863114e18f.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Sun Oct 16 2016 15:34:53 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>19</td></tr><tr><td>Device type</td><td>SM-T231</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>7% Unplugged</td></tr><tr><td>Memory free</td><td>141 MB / 1289 MB</td></tr></table>

 [Link to buddybuild feedback from build 19](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=58039e1d5ca741010019ccbc&bnum=19)

**Comment by rbeccapotter** [comment]
Answer 4 should trigger Prompt 1a (Please refer to nearest public facility). The other 3 answers are working. The prompt applies to all answers here.

**Comment by ifoche** [comment]
We change it
