### ISSUE TITLE
DE codes

### ISSUE THREAD

**Issue by rbeccapotter** [EyeSeeTea/SurveillanceLaosApp#39]
I think the semantics of the option set in the app is not matching the option code in DHIS for DE 'LA MAL SRV - RDT test result'

I was playing with data in PowerBI and I saw that cases in August showing up based on code Mixed, then in September, showing up as PfPv. It should match the code of the option in DHIS (which is 'Mixed' not 'PfPv'). Can you look at this?

**Comment by ifoche** [comment]
@rbeccapotter we've introduced this fix and the new translation system into the release that's about to be available.
