### ISSUE TITLE
Crashing in android 6.0.1

### ISSUE THREAD

**Issue by rbeccapotter** [EyeSeeTea/SurveillanceLaosApp#41]
The app is crashing in Android 6.0.1. Since we don't know what kind of Android devices providers use to report, it is important to fix.

**Comment by ifoche** [comment]
@rbeccapotter we have a solution for this already in the code, so we can produce a new release for you if you want it. It has to do with the new permissions style in Android 6. If you're really in a hurry, there's a way to do it even with the current code (a bit tricky) and consist on doing what's explained in [this link](http://www.howtogeek.com/230683/how-to-manage-app-permissions-on-android-6.0/). Do you want us to produce this new release?

**Comment by rbeccapotter** [comment]
@ifoche New release - yes please. Thank you.

**Comment by ifoche** [comment]
@rbeccapotter new release that's now being generated (you'll receive it in a few minutes) should properly work on Android 6.0. Please let me know if you find any problem

**Comment by rbeccapotter** [comment]
@ifoche  It seems to be working now. Can you update GooglePlay? Thanks for the quick fix.

**Comment by rbeccapotter** [comment]
Before updating, there is a different bug. We're seeing Q2 reason not tested in Khmer.

**Comment by ifoche** [comment]
oops, sorry. We'll generate a new release with this fix
