### ISSUE TITLE
kathelyn@psilaos.org on build #27: In lao version the script in this section is in khmer

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#43]
Feedback from kathelyn@psilaos.org : In lao version the script in this section is in khmer

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/583b3ccfd1b1540100ca7eae/7284f8aa-009b-4a28-97f6-e325208466eb.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Nov 28 2016 09:45:49 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>27</td></tr><tr><td>Device type</td><td>SM-J105B</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 800px</td></tr><tr><td>Battery</td><td>49% Unplugged</td></tr><tr><td>Memory free</td><td>142 MB / 705 MB</td></tr></table>

 [Link to buddybuild feedback from build 27](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=583bfccd39372d0100b7c2ea&bnum=27)

**Comment by rbeccapotter** [comment]
@ifoche  In the Laos version the questions are showing up in Khmer instead of Laos. Which I don't understand because I thought this text was embedded on this image. ?

**Comment by ifoche** [comment]
Hi @rbeccapotter. Yes, this is a bug we've introduced in last release. When we introduced the translation system (to automatically change text from one language to another) we also took advantage of this new system to store the images with the embedded text on every language and use this system to "translate" the path to the images. So when you're in Lao, the path to the image is translated into the path to an image with the embedded text in lao, and likewise for the rest of languages. Unfortunately, when we added the path for lao images, we made a mistake, and pointed them to images in khmer. This is very quick to fix and we're on it now. Sorry for the inconveniences

**Comment by ifoche** [comment]
new version is being generated. Please let me know if you find any other bug. Hopefully it will be ok.

**Comment by rbeccapotter** [comment]
@ifoche  Yup, it is working fine now. Can you release this on GPlay? Team will begin field testing tomorrow. Thanks

**Comment by ifoche** [comment]
upload completed, hopefully it won't take too much for it to be available in GPlay but let me know if you cannot download it or if you have any problem with GPlay version
