### ISSUE TITLE
Sent surveys dont show up in sent tab

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#44]
Feedback from rebecca@psilaos.org : Sent surveys dont show up in sent tab

![screenshot](https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/5903a35ca1f99f00017adb03/b7fe60ea-018a-44da-b3a1-4efc22c12331.jpg)

| Item | Value |
| --- | --- |
| Created | Sat May 27 2017 15:27:43 GMT+0000 (UTC) |
| App uptime | undefined |
| Build | 31 |
| Device type | SM-T231 |
| Device name | undefined |
| Screen size | 800 |
| Screen size | 800px by 1280px |
| Battery | 25% Unplugged |
| Memory free | 178 MB / 1289 MB |
| Network IP | undefined |

 [Link to buddybuild feedback from build 31](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=59299aefb9d0880001811045&bnum=31)

**Comment by ifoche** [comment]
Hi @rbeccapotter, could you provide me with server and credentials to replicate this issue? Thanks!

**Comment by Vbouasone** [comment]
I have some feedback on the new 1.2.0 MCS Laos testing in general the app work very well. however, I think some parts of the app need to be edited please refer to my report in PDF file.
[New MCS Laos app report.pdf](https://github.com/EyeSeeTea/SurveillanceLaosApp/files/1151851/New.MCS.Laos.app.report.pdf)
