### ISSUE TITLE
demo mode

### ISSUE THREAD

**Issue by rbeccapotter** [EyeSeeTea/SurveillanceLaosApp#45]
Can you hide the demo mode under developer options? I think KH disabled altogether; It's a feature we would like to keep in Laos but prefer to hide as much as possible from the end users (to disable demo mode, the user needs to re-log in to a real server -- yes?)

**Comment by ifoche** [comment]
sorry @rbeccapotter for the long wait. Yes, we'll go for it and create a new release once it's done
