### ISSUE TITLE
Pop up keyboard did not hide

### ISSUE THREAD

**Issue by Vbouasone** [EyeSeeTea/SurveillanceLaosApp#46]
On the phone number tab, once I fulfill the phone number the pop up key board did not disappear (even I hit “Done” button on the keyboard). Therefore, I can’t hit send button so I have to press “Back button” which is different from previous version and what we trained PPMs, it may confuse them.

![issue_1](https://user-images.githubusercontent.com/29400470/28261758-b537cd00-6b0a-11e7-8224-6a92bb0294a4.JPG)

**Comment by ifoche** [comment]
@Vbouasone can you try pressing the phone back button?

**Comment by Vbouasone** [comment]
@ifoche  Yes I can press the phone back button then the pop up keyboard disappear
