### ISSUE TITLE
The beginning and end of sentences of "Pv" pop up message are hidden

### ISSUE THREAD

**Issue by Vbouasone** [EyeSeeTea/SurveillanceLaosApp#48]
On the “Pv” pop up message, the beginning of sentence and the end of row the letters are hidden. Please fix this point as appropriate.

![issue_3](https://user-images.githubusercontent.com/29400470/28261974-8db1320c-6b0b-11e7-8041-0e9c08116130.JPG)

**Comment by ifoche** [comment]
Duplicate of #49
