### ISSUE TITLE
Hidden letters at the beginning and end of sentences

### ISSUE THREAD

**Issue by Vbouasone** [EyeSeeTea/SurveillanceLaosApp#49]
On the “Pf +Pv” pop up message, the beginning of sentence and the end of row the letters are hidden. Please fix this point as appropriate.
![issue_4](https://user-images.githubusercontent.com/29400470/28262132-27ccd508-6b0c-11e7-83cc-c1f47047e08a.JPG)

**Comment by ifoche** [comment]
Hi @Vbouasone, we're not able to replicate these layout problem. Could you please specify the Android version, device model and screen size? (for the screen size typically having the device model we can obtain it, but just in case)

**Comment by Vbouasone** [comment]
Hi Ignacia,

I tested on Samsung Galaxy Note 4 with the Android version 6.0.1, for the
details information please have a look in the link below


http://www.gsmarena.com/samsung_galaxy_note_4-6434.php

If you have any further question please let me know

Best,
Bouasone
