### ISSUE TITLE
clussiana@psi.org on build #5: Positivity rate right after Negative is a bit confusing,…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#5]
Feedback from clussiana@psi.org : 
@rbeccapotter
- Positivity rate right after Negative is a bit confusing, isn't it? Can we move it up by 1 row?
- The number of negative cases should match what below, so I'm not sure what "drug" refers to here. I found this confusing, but if you're ok with this, I am, too. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57b166ad632de401007bfee7/99af12f3-0f65-4664-92e9-eb18c89609ec.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Aug 17 2016 13:48:18 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>5</td></tr></table>

 [Link to buddybuild feedback from build 5](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57b46b22eb384e0100f3d9bf&bnum=5)

**Comment by ifoche** [comment]
Hi @cristinaelle, for now we've not changed the Positivity rate <-> Negative as we didn't received answer from @rbeccapotter, but we fix the negative cases, as they were not showing the proper number. Drug is in fact one of the reasons for not tested meaning that the user didn't have RDT stock to test. The direct translation from the Lao was drug following google translate and that's why it was there like that. We've changed the translation too.

**Comment by rbeccapotter** [comment]
@cristinaelle @ifoche @rodmelia There are a few discrepancies between monitor module and the specs...can we hold off on further tiny translation fixes/ordering of rows until we have a discussion with RM about the monitor module overall?  Lao team is translating Monitoring module in next 2 days to Lao, but we already had the English translations in specs..

**Comment by ifoche** [comment]
Hi @rbeccapotter, maybe this is a good opportunity to use the translation [server](https://poeditor.com/projects/po_edit?id_language=91&id=63217)? If you modify there the terms and you notify us, then we can produce a new version using directly your editions.
