### ISSUE TITLE
Hide letters at the beginning and end of sentences

### ISSUE THREAD

**Issue by Vbouasone** [EyeSeeTea/SurveillanceLaosApp#50]
On the “Reason not tested” pop up message, the beginning of sentence and the end of row the letters are hidden. Please fix this point as appropriate.
![issue_5](https://user-images.githubusercontent.com/29400470/28262239-83e21128-6b0c-11e7-9f22-d54a4c6e5347.JPG)

**Comment by ifoche** [comment]
@Vbouasone see question in #49
