### ISSUE TITLE
Hide letters in pop up message

### ISSUE THREAD

**Issue by Vbouasone** [EyeSeeTea/SurveillanceLaosApp#51]
On the “ACT Out of stock” pop up message, the beginning of sentence and the end of row the letters are hidden. Please fix this point as appropriate.
![issue_6](https://user-images.githubusercontent.com/29400470/28262491-5bae5008-6b0d-11e7-8aff-84ed8e81e6de.JPG)

**Comment by ifoche** [comment]
Duplicate of #49
