### ISSUE TITLE
The second button contains unnecessary letters

### ISSUE THREAD

**Issue by Vbouasone** [EyeSeeTea/SurveillanceLaosApp#52]
On the “Invalid result” tab, the beginning of sentence and the end of row the letters are hidden. Please fix this point as appropriate. The second button contains unnecessary letters
![issue_7](https://user-images.githubusercontent.com/29400470/28262709-317d572e-6b0e-11e7-9390-d3ba49c1b7df.JPG)
.

**Comment by ifoche** [comment]
@Vbouasone please see question in #49
