### ISSUE TITLE
new version of MCS lao app can not send data to production server

### ISSUE THREAD

**Issue by Vbouasone** [EyeSeeTea/SurveillanceLaosApp#57]
I tried to submit data to production server by using new version of MCS lao app with PPMs' org units under MDs' usernames, but there is no single org unit can send data to production server except Laos testing org unit. Please tackle this issue for us.

**Comment by ifoche** [comment]
Hi @Vbouasone. I don't have permissions in production server, but it seems to me that the problem may come from the fact that the app is using a single user to send all the information, and that user may not have permissions to capture data for the rest of the OUs you need to send info to.

Can you confirm that LAMCS user has permissions for the OUs that you're to send data to?

@rbeccapotter I'm not sure if it's a question for @Vbouasone or for you...I'm not sure who takes care of the server.

**Comment by rbeccapotter** [comment]
@ifoche I was seeing the same problem. I also thought it was the dummy user org unit (LAMCS) assignment, but I checked this earlier and it was assigned to the proper OUs. Usually, Jose takes care of this server for Asia's countries but I cannot flag him here. Maybe @rodmelia or @purdych1 can help. Now the server is doing crazy things that I believe are unrelated - I cannot even see data elements, etc.

@Vbouasone , was this a problem in the last BuddyBuild version? Or only when testing the Gplay in data.psi-mis.org? Can you please confirm 1) if it is experienced with Buddybuild, or jsut Gplay version and 2) is this only a problem in data.psi-mis.org or do you also have the problem in staging.psi-mis.org?  As much as you can isolate the problem, it will be helpful for trouble shooting, Unfortunately I'm in the field and unlikely to be able to test fully for at least one more day.

**Comment by rbeccapotter** [comment]
@Vbouasone I'm not 100% sure, but I think there is an error in configuration of user assignment to OUs. The dummy OU 'LAMCS' looks ok to me.  I looked at your user bouasonev and it is not assigned to the individual org units (i.e. LAMAL160303). If this behavior is like other mobile apps, the user must be assigned to each individual org unit (PPM outlet). It cannot just be assigned to "Laos". 

I started from scratch and completed the following steps:
1) created test user
2) assigned user to individual testing Org Units and to user roles (_user Data entry SEwoR, LA MAL - SRV)
3) assigned user to LA - User group
4) Assigned test OUs to program LA MAL - Surveillance App
5) Checked that the dummy user LAMCS was assigned to test OUs -- yes

I was able to push the data to the server on testing org unit. So I am not sure why this isn't working for other org units IF you can also verify that all steps 1-5 are completed correctly. **Note: we know there is a bug for assigning the dummy org unit LAMCS to more than 200 OUs, and I used a workaround**

That being said, I'm now trying to test one of your real org units and I cannot get the app to search the org unit (starting with CL) to assign it on the app. I honestly don't know. @Vbouasone if you can confirm if it was 1) problem in last buddybuild or only a problem in Gplay release, and 2) is it a problem in data.psi-mis.org only, or also in another server (i.e. staging.psi-mis.org), it would be helpful to isolate the problem.

**Comment by ifoche** [comment]
@rbeccapotter may the problem come from the unique user that's sending everything behind the scenes? In MCS Laos the user LAMCS is responsible for sending everything, so even if you login with another user, the data will be uploaded by LAMCS. If that user is not activated for those other OUs, the server won't accept the data. Could that be the problem?

**Comment by rbeccapotter** [comment]
@ifoche no, that's not the problem. I checked that first, but LAMCS is assigned to the individual org units properly. I am not sure why now, I cannot search for org units to select on the app. It just shows blank every time (I am 100% sure my user is configured properly). Usually I can type in the first letter and then it gives me a dropdown of users assigned to my account that I can select.

**Comment by rbeccapotter** [comment]
I suspect it's a server side configuration error but I can't figure out what. 
Org Unit: LAMAL140114
1) Assigned to Program? yes
2) Assigned to LAMCS user? Yes

But it does not send data to the server. Am I missing something?

**Comment by ifoche** [comment]
@rbeccapotter can you please send me by email the credentials for the test user? Maybe I can tell you more looking at the debug messages of the app (i.e. if the server is answering that the user doesn't have permissions or something like that)

**Comment by Vbouasone** [comment]
@rbeccapotter to answer you question *1) problem in last buddybuild or only
a problem in Gplay release,*

the problem is in Gplay release because once I tested the last buddybuild I
did not face this issue,


 *and 2) is it a problem in **data.psi-mis.org
<http://data.psi-mis.org/> only, or also in another server
(i.e. staging.psi-mis.org <http://staging.psi-mis.org/>)*

This problem happened in data.psi-mis.org only, when I tested on the
staging.psi-mis.org the data was submitted and everything look good.

**Comment by ifoche** [comment]
It was a problem with a library that the app's using. Now should be fixed in the last bb version.

**Comment by ifoche** [comment]
Oh, and just for the record, the problem was related to the creation of URL requests using Lao characters. This happened when the OU name was written in Lao

**Comment by Vbouasone** [comment]
Noted, I tried with 11 PPMs' account and each PPM account can send data to
production server perfectly.
