### ISSUE TITLE
clussiana@psi.org on build #5: When someone gets to this review screen, the header says…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#8]
Feedback from clussiana@psi.org : When someone gets to this review screen, the header says "Check before submission". In case something is not correct, the user can't go back and modify it because from here the user just has 2 options: submit or delete. @rbeccapotter : Do we want to offer the possibility to review the survey in case something is not right?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57b166ad632de401007bfee7/e2d75ab3-e32a-4105-8bfe-e81687bd5928.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Aug 17 2016 16:13:56 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>5</td></tr></table>

 [Link to buddybuild feedback from build 5](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57b48d444d7d6a01002feddb&bnum=5)

**Comment by rbeccapotter** [comment]
@cristinaelle @rodmelia The flow for review and submit still does not make sense to me in Build 10. It should load "Please check before transmission" screen first (so user can see their answers), then "Review or submit" pop up.

**Comment by ifoche** [comment]
@rbeccapotter @cristinaelle. Maybe this is a problem with the pop-up text and not with the flow? I'm meaning: currently, if you finish a survey it ask you if you want to send it or review it one by one, if you choose send, then it takes you to the review screen, which contains all your answers (still not sent), and only if you choose to go on, then the survey is sent. If from the review screen you swipe right (to go back) or you simply press on the back button, you go back to the survey and are able to review one by one the questions of the survey.

Maybe we would need to remove that prompt and put it at the end just after the review screen?

**Comment by rbeccapotter** [comment]
@ifoche As discussed, the "Survey Complete Review/Submit" pop-up should come after the summary screen (right now, it pops up before Cristina's summary screenshot). 

Also, would like the user to be able to select the question they want to edit and link back to that question in the survey. From there, the user will have to complete the rest of the survey (because of the logic flows).

**Comment by rbeccapotter** [comment]
Tested this and I love it! So much better - the hyperlinks  to question that we want to change also seem to be working.
